global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alerting config
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:9464']
    metrics_path: '/metrics'

  - job_name: 'accounting-service'
    static_configs:
      - targets: ['accounting-service:9464']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:9464']
    metrics_path: '/metrics'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9464']
    metrics_path: '/metrics'

  - job_name: 'app-mobile-service'
    static_configs:
      - targets: ['app-mobile-service:9464']
    metrics_path: '/metrics'

  - job_name: 'portfolio-institution-service'
    static_configs:
      - targets: ['portfolio-institution-service:9464']
    metrics_path: '/metrics'

  - job_name: 'customer-service'
    static_configs:
      - targets: ['customer-service:9464']
    metrics_path: '/metrics'

  - job_name: 'adha-ai-service'
    static_configs:
      - targets: ['adha-ai-service:9464']
    metrics_path: '/metrics'
    scrape_interval: 15s
    metrics_path: '/metrics'
      
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
