# Generated by Django 4.2.20 on 2025-04-11 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_merge_20240820_xxxx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tokenpurchaserequest',
            options={},
        ),
        migrations.RenameField(
            model_name='tokenpurchaserequest',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='api_userpro_user_ty_4f307f_idx',
            old_name='api_userpro_user_ty_e25dcc_idx',
        ),
        migrations.RemoveField(
            model_name='tokenprice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tokenprice',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='tokenprice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tokenpurchaserequest',
            name='approval_date',
        ),
        migrations.RemoveField(
            model_name='tokenpurchaserequest',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='tokenprice',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='tokenprice',
            name='effective_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tokenpurchaserequest',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='tokenpurchaserequest',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('other', 'Other')], default='bank_transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='tokenpurchaserequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tokenpurchaserequest',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_token_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tokenpurchaserequest',
            name='processed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tokenprice',
            name='price_per_million',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tokenpurchaserequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_requests', to='api.company'),
        ),
        migrations.AlterField(
            model_name='tokenpurchaserequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokenpurchaserequest',
            name='tokens_requested',
            field=models.BigIntegerField(),
        ),
    ]
