# Generated by Django 4.2.20 on 2025-04-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tokenprice_options_and_more'),
        ('api', 'update_company_subscriptions'),
    ]

    operations = [
    ]
