# Generated by Django 4.2.20 on 2025-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250411_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_subscription_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='monthly_token_allowance',
            field=models.BigIntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='token_quota',
            field=models.BigIntegerField(default=1000000),
        ),
    ]
