# Generated by Django 4.2.20 on 2025-04-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_is_subscription_active_and_more'),
        ('api', 'add_token_usage_fields'),
    ]

    operations = [
    ]
