# Generated by Django 4.2.20 on 2025-04-11 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_merge_20250411_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_tokens', models.BigIntegerField(default=1000000)),
                ('tokens_used', models.BigIntegerField(default=0)),
                ('reset_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('never', 'Never')], default='monthly', max_length=20)),
                ('next_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tokenusage',
            options={'verbose_name': 'Token Usage', 'verbose_name_plural': 'Token Usage'},
        ),
        migrations.RemoveIndex(
            model_name='tokenusage',
            name='api_tokenus_operati_5027f3_idx',
        ),
        migrations.RemoveField(
            model_name='tokenquota',
            name='last_reset',
        ),
        migrations.RemoveField(
            model_name='tokenquota',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='tokenquota',
            name='price_per_million',
        ),
        migrations.RemoveField(
            model_name='tokenquota',
            name='reset_period',
        ),
        migrations.RemoveField(
            model_name='tokenquota',
            name='tokens_used',
        ),
        migrations.RemoveField(
            model_name='tokenquota',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='input_tokens',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='tokenusage',
            name='output_tokens',
        ),
        migrations.AddField(
            model_name='tokenusage',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokenquota',
            name='next_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['model'], name='api_tokenus_model_71a922_idx'),
        ),
        migrations.AddField(
            model_name='usertokenquota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_quota', to=settings.AUTH_USER_MODEL),
        ),
    ]
