# Generated by Django 5.2 on 2025-04-09 20:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Écriture comptable', 'verbose_name_plural': 'Écritures comptables'},
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='debit_account',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='piece_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
